In [1]:
using DataStructures

In [17]:
using LinearAlgebra

In [54]:
(prod_el) = open("25_1.txt") do f

    graph = DefaultDict(() -> [])

    for l in eachline(f) 
        values = split(l, ": ")
        lhs = values[1]
        for rhs in split(values[2], " ")
            push!(graph[lhs], rhs)
            push!(graph[rhs], lhs)
        end
    end
    println(graph)

    
    names_to_idx = Dict()
    idx_to_names = Dict()

    for (idx, name) in enumerate(keys(graph))
        names_to_idx[name] = idx
        idx_to_names[idx] = name
    end

    # Create the adjacency matrix, hoping to have enough RAM
    n = length(keys(graph))
    adj_mat = zeros(Int32, n, n)
    println(names_to_idx)

    for (idx, name) in enumerate(keys(graph))
        for a_connection in graph[name]
            adj_mat[names_to_idx[name], names_to_idx[a_connection]] = 1
        end
    end

    display(adj_mat)

    lap = Matrix(1I, n, n) 
    for (idx,i) in enumerate(sum(adj_mat, dims = 1))
        lap[idx,idx] = i
    end
    lap = lap - adj_mat

    display(lap)

    evals = eigvals(lap)
    evect = eigvecs(lap)

    println(evals)
    fiedler = evect[:,2]
    println(fiedler)

    npos = length(findall(x -> x > 0, fiedler))
    out = npos*(n-npos)

    (out)

end


DefaultDict{Any, Any, var"#94#97"}("lpk" => Any["mfh", "rzj", "hhl", "zxq", "dfd"], "hpp" => Any["tkk", "htt", "zlj", "rxd"], "kms" => Any["fgx", "nrb", "xxj", "nvf", "mbx"], "zfz" => Any["cpz", "bgk", "krb", "sft"], "grh" => Any["gtx", "nzc", "zrv", "hbg"], "slb" => Any["lns", "mdb", "ktl", "dkv"], "htc" => Any["fxd", "llb", "vgs", "mdb", "spf"], "jgq" => Any["tjc", "vzd", "hdc", "rrj", "tfz"], "kbg" => Any["vhz", "tmn", "jnf", "rzj"], "ksj" => Any["sct", "tvt", "gjs", "nfg", "kkh", "ccz"], "ghf" => Any["tbb", "dhd", "kxb", "bnp"], "pcd" => Any["kjg", "lvk", "vng", "nkf"], "vcr" => Any["xcf", "pxn", "jsp", "shm", "zcc"], "mdj" => Any["cjr", "bgk", "jms", "xsg", "xrb", "pfd"], "tvb" => Any["pqb", "xxx", "zxb", "pvd"], "cqt" => Any["gkd", "gpj", "qht", "krn"], "djj" => Any["ktq", "ttk", "xxx", "ctb"], "lvk" => Any["htt", "pcd", "dbx", "ncj"], "nkj" => Any["sbl", "svr", "pxb", "krb", "rzr"], "tpk" => Any["tlp", "rdb", "jnt", "kpl"], "xrb" => Any["vdc", "mmt", "zsr", "mdj"], "sdc" => Any[

1503×1503 Matrix{Int32}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  1  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0 

1503×1503 Matrix{Int64}:
 5  0  0  0  0  0   0  0  0  0  0  0  …  0  0  0  0  0  0   0  0  0  0  0  0
 0  4  0  0  0  0   0  0  0  0  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  5  0  0  0   0  0  0  0  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  4  0  0   0  0  0  0  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  4  0   0  0  0  0  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  4   0  0  0  0  0  0  …  0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  0   5  0  0  0  0  0     0  0  0  0  0  0  -1  0  0  0  0  0
 0  0  0  0  0  0   0  5  0  0  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  0   0  0  4  0  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  0   0  0  0  6  0  0     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  0   0  0  0  0  4  0  …  0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  0   0  0  0  0  0  4     0  0  0  0  0  0   0  0  0  0  0  0
 0  0  0  0  0  0   0  0  0  0  0  0     0  0  0  0

[-2.017745283972494e-14, 0.004582630558726846, 0.7633142066853317, 0.7688720880066211, 0.7790357605591522, 0.7821019921999721, 0.7987813203031557, 0.812252641860833, 0.8146749188614427, 0.8193402797478327, 0.8310501515703566, 0.8331428877711929, 0.8419222715272002, 0.8422588078925872, 0.8540433611971744, 0.8662401404022828, 0.8690957127934476, 0.8788021866534501, 0.8846980558168629, 0.8907189594300164, 0.8993124522628593, 0.9073571188903788, 0.9130335475098926, 0.915512011957845, 0.916672584503667, 0.9247413987461903, 0.9331404462647144, 0.9359215791061897, 0.9388346630709553, 0.9462713863969496, 0.9496331820483793, 0.9564762780889066, 0.9635344831340672, 0.9649058498385741, 0.9691552575043184, 0.9807164240118882, 0.9830760381911892, 0.9872417096599627, 0.9920046133562058, 0.994486621183928, 1.0011821837482544, 1.002761035244498, 1.014370357288498, 1.0157970812585593, 1.0196010069262897, 1.0225361963947424, 1.0330209660591563, 1.0400810905395579, 1.0534674169048408, 1.0540834727729722,

562772

In [4]:
split("frs: qnr lhk lsr", ": ")

2-element Vector{SubString{String}}:
 "frs"
 "qnr lhk lsr"

In [8]:
zeros(Int64, 2,2)

2×2 Matrix{Int64}:
 0  0
 0  0

In [29]:
A = Matrix(1I, 3, 3)
B = zeros(Int, 3,3)
B[1,2] = 1
B[2,1] = 1
B[1,3] = 1
B[3, 1] = 1

1

In [30]:
sum(B, dims = 1)

1×3 Matrix{Int64}:
 2  1  1

In [34]:
A * Diagonal(Vector(sum(B, dims = 1)))

LoadError: MethodError: no method matching (Vector)(::Matrix{Int64})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.

Closest candidates are:
  (Array{T, N} where T)(::AbstractArray{S, N}) where {S, N}
   @ Core boot.jl:498
  (Vector)()
   @ Base baseext.jl:38
  (Vector)(::SparseArrays.AbstractSparseVector{Tv}) where Tv
   @ SparseArrays C:\Users\jbouchot\AppData\Local\Programs\Julia-1.9.4\share\julia\stdlib\v1.9\SparseArrays\src\sparsevector.jl:1052
  ...


In [28]:
(ones(Int,3,1)*sum(B, dims = 1))

3×3 Matrix{Int64}:
 1  1  0
 1  1  0
 1  1  0

In [40]:
Diagonal([i for i in (sum(B, dims = 1))])

1×1 Diagonal{Int64, Vector{Int64}}:
 2

In [39]:
[i for i in Array(sum(B, dims = 1))]

1×3 Matrix{Int64}:
 2  1  1

In [41]:
for i in sum(B, dims=1)
    println(i)
end

2
1
1
