In [3]:
function is_parallel(speed1, speed2)
    return speed1[1]*speed2[2] == speed1[2]*speed2[1]
end

is_parallel (generic function with 1 method)

In [4]:
is_parallel([-1, -1, -2], [-2, -2, -4])

true

In [1]:
function parse_line(a_line)
    values = split(a_line, " @ ")
    positions = [parse(Int, v) for v in split(values[1], ", ")]
    speeds = [parse(Int, v) for v in split(values[2], ", ")]
    return (positions, speeds)
end

parse_line (generic function with 1 method)

In [2]:
parse_line("20, 19, 15 @  1, -5, -3")

([20, 19, 15], [1, -5, -3])

In [46]:
function check_range(ray1, ray2, min_v, max_v)
    p1 = ray1[1]
    p2 = ray2[1]
    s1 = ray1[2]
    s2 = ray2[2] 
    r1 = s1[2] / s1[1]
    r2 = s2[2] / s2[1]
    # println("Ray 1 is $ray1 and Ray 2 is $ray2")
    x_star = (p2[2]-p1[2] + r1*p1[1] - r2*p2[1]) / (r1 - r2)
    # println("x star is $x_star")
    if (x_star < min_v) || (x_star > max_v) || (x_star*s1[1] < p1[1]*s1[1]) || (x_star*s2[1] < p2[1]*s2[1])
        return false
    else
        y_star = r1*(x_star - p1[1]) + p1[2]
        # println("y star is $y_star")
        if (y_star < min_v) || (y_star > max_v)
            return false
        else 
            # println("Yes indeed!")
            return true
        end
    end
    
end

check_range (generic function with 1 method)

In [47]:
check_range(parse_line("18, 19, 22 @ -1, -1, -2"), parse_line("12, 31, 28 @ -1, -2, -1"), 7, 27)

false

In [48]:
check_range(parse_line("19, 13, 30 @ -2, 1, -2"), parse_line("18, 19, 22 @ -1, -1, -2"), 7, 27)

true

In [50]:
nb_intersect = open("24_1.txt") do f
    nb_i = 0

    rays = []
    min_v = 200000000000000
    max_v = 400000000000000

    for l in eachline(f)
        push!(rays, parse_line(l))
    end

    for (idx,r1) in enumerate(rays)
        for r2 in rays[idx+1:end]
            if !is_parallel(r1[2], r2[2])
                nb_i = check_range(r1, r2, min_v, max_v) ? nb_i+1 : nb_i
            end
        end
    end

    (nb_i)
    
    
end

26657

In [61]:
sum_position = open("24_1.txt") do f
    X = 1
    Y = 2
    Z = 3

    rays = []
    min_v = 200000000000000
    max_v = 400000000000000

    for l in eachline(f)
        push!(rays, parse_line(l))
    end

    # Select 3 random equations to set up the problem
    ids = [1, 2, 5]

    (p1, s1) = rays[ids[1]]
    (p2, s2) = rays[ids[2]]
    (p3, s3) = rays[ids[3]]
    println("P1 is $p1, s1 is $s1")
    println("P2 is $p2, s2 is $s2")
    println("P3 is $p3, s3 is $s3")

    A_mat = zeros(6,6)
    A_mat[1,1] = s1[Y] - s2[Y]
    A_mat[1,2] = s2[X] - s1[X]
    A_mat[1,4] = p2[Y] - p1[Y]
    A_mat[1,5] = p1[X] - p2[X]

    A_mat[2,1] = s2[Y] - s3[Y]
    A_mat[2,2] = s3[X] - s2[X]
    A_mat[2,4] = p3[Y] - p2[Y]
    A_mat[2,5] = p2[X] - p3[X]

    A_mat[3,1] = s1[Z] - s2[Z]
    A_mat[3,3] = s2[X] - s1[X]
    A_mat[3,4] = p2[Z] - p1[Z]
    A_mat[3,6] = p1[X] - p2[X]

    A_mat[4,1] = s2[Z] - s3[Z]
    A_mat[4,3] = s3[X] - s2[X]
    A_mat[4,4] = p3[Z] - p2[Z]
    A_mat[4,6] = p2[X] - p3[X]

    A_mat[5,2] = s1[Z] - s2[Z]
    A_mat[5,3] = s2[Y] - s1[Y]
    A_mat[5,5] = p2[Z] - p1[Z]
    A_mat[5,6] = p1[Y] - p2[Y]

    A_mat[6,2] = s2[Z] - s3[Z]
    A_mat[6,3] = s3[Y] - s2[Y]
    A_mat[6,5] = p3[Z] - p2[Z]
    A_mat[6,6] = p2[Y] - p3[Y]

    b_vec = zeros(6,1)
    b_vec[1] = p2[X]*s2[Y] - p1[X]*s1[Y] + p1[Y]*s1[X] - p2[Y]*s2[X]
    b_vec[2] = p3[X]*s3[Y] - p2[X]*s2[Y] + p2[Y]*s2[X] - p3[Y]*s3[X]
    b_vec[3] = p2[X]*s2[Z] - p1[X]*s1[Z] + p1[Z]*s1[X] - p2[Z]*s2[X]
    b_vec[4] = p3[X]*s3[Z] - p2[X]*s2[Z] + p2[Z]*s2[X] - p3[Z]*s3[X]
    b_vec[5] = -(p2[Z]*s2[Y] - p1[Z]*s1[Y] + p1[Y]*s1[Z] - p2[Y]*s2[Z])
    b_vec[6] = -(p3[Z]*s3[Y] - p2[Z]*s2[Y] + p2[Y]*s2[Z] - p3[Y]*s3[Z])

    display(A_mat)
    display(b_vec)

    x = A_mat \ (-b_vec)

    println(x)
    
    
    

    (x[1] + x[2]+ x[3])
    
    
end

P1 is [313743533208081, 328167831228390, 159732064722764], s1 is [51, 115, 83]
P2 is [468183773350185, 269960480220160, 439515864552130], s2 is [-243, -42, -12]
P3 is [317004666243105, 378324701560288, 371293866971580], s3 is [-85, -156, -21]


6×6 Matrix{Float64}:
 157.0  -294.0     0.0  -5.82074e13  -1.5444e14    0.0
 114.0   158.0     0.0   1.08364e14   1.51179e14   0.0
  95.0     0.0  -294.0   2.79784e14   0.0         -1.5444e14
   9.0     0.0   158.0  -6.8222e13    0.0          1.51179e14
   0.0    95.0  -157.0   0.0          2.79784e14   5.82074e13
   0.0     9.0  -114.0   0.0         -6.8222e13   -1.08364e14

6×1 Matrix{Float64}:
  2.6592731286509684e16
 -6.323180651409101e16
  8.328977185055562e16
 -7.628126910448627e16
  6.35139799970903e15
  3.4756883966252892e16

[3.3584999088405506e14; 3.6249462886189006e14; 1.3007371156741992e14; -109.99999999999999; -135.0000000000001; 299.00000000000017;;]


8.28418331313365e14

In [52]:
zeros(6,6)

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0